[package]
name = "client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gloo = "0.11.0"
serde = "1.0.225"
serde_json = "1.0.145"
wasm-bindgen = "0.2.103"
web-sys = "0.3.80"
